name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarQubeScan1:
    name: sonarQubeScan1
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v4 #this installs node and npm for us
        with:
          node-version: '10.x'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: |
          npm install
          npm run-script deploy
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Use the current directory as the build context
          file: Dockerfile  # Specify the Dockerfile to use
          tags: localpytest:latest  # Tag for the built image
          load: true  # Load the image into the Docker daemon (for local use)
          cache-from: type=gha  # Use GitHub Actions cache as a cache source
          cache-to: type=gha,mode=max  # Store cache in GitHub Actions for future builds
          push: false  # Do not push to a remote registry (set to true if you want to push)
